"""add analysis tables

Revision ID: 2cd114a9d495
Revises: 09380ec394d2
Create Date: 2026-04-15 14:59:31.190756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd114a9d495'
down_revision: Union[str, None] = '09380ec394d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_ratios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('de_ratio', sa.Float(), nullable=True),
    sa.Column('revenue_qoq', sa.Float(), nullable=True),
    sa.Column('revenue_yoy', sa.Float(), nullable=True),
    sa.Column('profit_qoq', sa.Float(), nullable=True),
    sa.Column('profit_yoy', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('book_value_per_share', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'year', 'period', name='uq_financial_ratio')
    )
    op.create_index(op.f('ix_financial_ratios_symbol'), 'financial_ratios', ['symbol'], unique=False)
    op.create_table('industry_averages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('avg_pe', sa.Float(), nullable=True),
    sa.Column('avg_pb', sa.Float(), nullable=True),
    sa.Column('avg_roe', sa.Float(), nullable=True),
    sa.Column('avg_roa', sa.Float(), nullable=True),
    sa.Column('avg_de', sa.Float(), nullable=True),
    sa.Column('avg_revenue_growth_yoy', sa.Float(), nullable=True),
    sa.Column('avg_profit_growth_yoy', sa.Float(), nullable=True),
    sa.Column('stock_count', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code', 'year', 'period', name='uq_industry_average')
    )
    op.create_index(op.f('ix_industry_averages_group_code'), 'industry_averages', ['group_code'], unique=False)
    op.create_table('industry_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('group_name_vi', sa.String(length=200), nullable=False),
    sa.Column('group_name_en', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code')
    )
    op.create_table('stock_industry_mapping',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('group_code', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stock_industry_mapping_group_code'), 'stock_industry_mapping', ['group_code'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_26', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('stoch_k', sa.Float(), nullable=True),
    sa.Column('stoch_d', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('obv', sa.BigInteger(), nullable=True),
    sa.Column('avg_volume_20', sa.BigInteger(), nullable=True),
    sa.Column('relative_volume', sa.Float(), nullable=True),
    sa.Column('volume_trend', sa.String(length=20), nullable=True),
    sa.Column('trend_direction', sa.String(length=20), nullable=True),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('pivot_point', sa.Float(), nullable=True),
    sa.Column('support_1', sa.Float(), nullable=True),
    sa.Column('support_2', sa.Float(), nullable=True),
    sa.Column('resistance_1', sa.Float(), nullable=True),
    sa.Column('resistance_2', sa.Float(), nullable=True),
    sa.Column('nearest_support', sa.Float(), nullable=True),
    sa.Column('nearest_resistance', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_technical_indicator')
    )
    op.create_index('ix_tech_indicators_symbol_date', 'technical_indicators', ['symbol', 'date'], unique=False)
    op.create_index(op.f('ix_technical_indicators_date'), 'technical_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_technical_indicators_symbol'), 'technical_indicators', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_indicators_symbol'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_date'), table_name='technical_indicators')
    op.drop_index('ix_tech_indicators_symbol_date', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_stock_industry_mapping_group_code'), table_name='stock_industry_mapping')
    op.drop_table('stock_industry_mapping')
    op.drop_table('industry_groups')
    op.drop_index(op.f('ix_industry_averages_group_code'), table_name='industry_averages')
    op.drop_table('industry_averages')
    op.drop_index(op.f('ix_financial_ratios_symbol'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    # ### end Alembic commands ###
