"""add phase3 sentiment scoring tables

Revision ID: c4007f49f9a7
Revises: 2cd114a9d495
Create Date: 2026-04-15 18:33:32.080933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4007f49f9a7'
down_revision: Union[str, None] = '2cd114a9d495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composite_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('macro_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=2), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('dimensions_used', sa.Integer(), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_composite_score')
    )
    op.create_index(op.f('ix_composite_scores_date'), 'composite_scores', ['date'], unique=False)
    op.create_index(op.f('ix_composite_scores_symbol'), 'composite_scores', ['symbol'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_feed', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_news_articles_published', 'news_articles', ['published_at'], unique=False)
    op.create_index('ix_news_articles_source', 'news_articles', ['source'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('sentiment', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'symbol', name='uq_sentiment_score')
    )
    op.create_index(op.f('ix_sentiment_scores_article_id'), 'sentiment_scores', ['article_id'], unique=False)
    op.create_index(op.f('ix_sentiment_scores_symbol'), 'sentiment_scores', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_scores_symbol'), table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_article_id'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index('ix_news_articles_source', table_name='news_articles')
    op.drop_index('ix_news_articles_published', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_composite_scores_symbol'), table_name='composite_scores')
    op.drop_index(op.f('ix_composite_scores_date'), table_name='composite_scores')
    op.drop_table('composite_scores')
    # ### end Alembic commands ###
