"""add phase4 macro report tables

Revision ID: a1b2c3d4e5f6
Revises: c4007f49f9a7
Create Date: 2026-04-16 03:57:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "c4007f49f9a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "macro_indicators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("indicator_type", sa.String(length=30), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("trend", sa.String(length=20), nullable=True),
        sa.Column("recorded_at", sa.Date(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("indicator_type", "period", name="uq_macro_indicator"),
    )
    op.create_table(
        "analysis_reports",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("report_type", sa.String(length=20), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.String(length=20), nullable=False),
        sa.Column("t3_prediction", sa.String(length=20), nullable=True),
        sa.Column("model_used", sa.String(length=50), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("grade", sa.String(length=2), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "date", "report_type", name="uq_analysis_report"),
    )
    op.create_index(
        op.f("ix_analysis_reports_symbol"), "analysis_reports", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_reports_date"), "analysis_reports", ["date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_reports_date"), table_name="analysis_reports")
    op.drop_index(op.f("ix_analysis_reports_symbol"), table_name="analysis_reports")
    op.drop_table("analysis_reports")
    op.drop_table("macro_indicators")
    # ### end Alembic commands ###
